runtime: nodejs20
service: default

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 20

handlers:
- url: /.*
  script: auto
  secure: always